apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '55.11.x'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 1m
  values:
    prometheus:
      prometheusSpec:
        podMonitorNamespaceSelector: { }
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
