apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-ingress
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    istio: istio=ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "istio.alpha.now-u.com"
