apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-system.yaml
  - namespace-ingress.yaml
  - repository-istio.yaml
  - release-base.yaml
  - release-istiod.yaml
  - release-gateway.yaml

  - namespace-kiali.yaml
  - repository-kiali.yaml
  - release-kiali.yaml
