apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: kiali-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: kiali-operator
      version: '1.79.0'
      sourceRef:
        kind: HelmRepository
        name: kiali
      interval: 1m
  values:
    cr:
      create: true
      namespace: istio-system

