apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: meilisearch
spec:
  interval: 5m
  chart:
    spec:
      chart: meilisearch/meilisearch
      version: '0.4.0'
      sourceRef:
        kind: HelmRepository
        name: meilisearch
      interval: 1m
